M48
; DRILL file {KiCad 7.0.10} date Mon Feb 12 10:02:05 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-02-12T10:02:05+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0394
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0512
%
G90
G05
T1
X3.4055Y-2.2819
X3.4055Y-2.3819
X3.4055Y-2.4819
T2
X2.1927Y-2.262
X2.1927Y-2.462
M30
