M48
; DRILL file {KiCad 8.0.5} date 2025-02-11T15:16:58+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-02-11T15:16:58+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0472
%
G90
G05
T1
X5.18Y-5.14
T2
X5.185Y-5.295
X5.3228Y-5.295
X5.4606Y-5.295
M30
