M48
; DRILL file {KiCad 7.0.10} date Wed Feb 14 16:45:12 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-02-14T16:45:12+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0512
%
G90
G05
T1
X7.175Y-5.3
X7.175Y-5.5
X7.175Y-5.7
X7.175Y-5.9
X7.175Y-6.1
X7.175Y-6.3
X7.175Y-6.5
M30
