M48
; DRILL file {KiCad 7.0.7} date Sat Feb 24 14:04:37 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-02-24T14:04:37+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1280
%
G90
G05
T1
X5.3937Y-3.563
X5.3937Y-4.4488
T2
X5.9693Y-4.0913
X5.9693Y-4.4913
X5.9764Y-3.5008
X5.9764Y-3.9008
T0
M30
